baseURL = 'http://linson.hugo.decap.s3-website-ap-southeast-2.amazonaws.com'
languageCode = 'en-us'
title = 'My New Hugo Site'


[[module.imports]]
path = 'github.com/gethinode/hinode'


defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
